"""Add image_path to projects

Revision ID: 098f8994c395
Revises: 4125f251a26a
Create Date: 2025-07-16 15:43:19.666079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '098f8994c395'
down_revision: Union[str, None] = '4125f251a26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('projects', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.alter_column('projects', 'with_image',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('projects_created_by_user_id_fkey'), 'projects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('projects_created_by_user_id_fkey'), 'projects', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('projects', 'with_image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('projects', 'image_path')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
