"""Add images column to post

Revision ID: 2a6dff0afdf4
Revises: 5cea23154bff
Create Date: 2025-07-11 15:18:15.484067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a6dff0afdf4'
down_revision: Union[str, None] = '5cea23154bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('post', sa.Column('texts', sa.JSON(), nullable=False))
    op.add_column('post', sa.Column('images', sa.JSON(), nullable=False))
    op.drop_column('post', 'text')
    op.alter_column('scheduled_posts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('scheduled_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scheduled_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scheduled_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scheduled_posts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('post', sa.Column('text', sa.VARCHAR(length=63206), autoincrement=False, nullable=False))
    op.drop_column('post', 'images')
    op.drop_column('post', 'texts')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
