"""Add status to Project

Revision ID: 2c01a44cda31
Revises: b575720360cd
Create Date: 2025-07-21 14:26:55.749603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c01a44cda31'
down_revision: Union[str, None] = 'b575720360cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('projects', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('social_credentials', sa.Column('ig_username', sa.String(), nullable=True))
    op.add_column('social_credentials', sa.Column('ig_password', sa.String(), nullable=True))
    op.drop_column('social_credentials', 'ig_graph_access_token')
    op.drop_column('social_credentials', 'ig_user_id')
    op.alter_column('social_media_credentials', 'twitter_access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'twitter_access_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'linkedin_access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'discord_webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('social_media_credentials', 'ig_graph_access_token')
    op.drop_column('social_media_credentials', 'ig_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_credentials', sa.Column('ig_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('social_media_credentials', sa.Column('ig_graph_access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('social_media_credentials', 'discord_webhook_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'linkedin_access_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'twitter_access_secret',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('social_media_credentials', 'twitter_access_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('social_credentials', sa.Column('ig_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('social_credentials', sa.Column('ig_graph_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('social_credentials', 'ig_password')
    op.drop_column('social_credentials', 'ig_username')
    op.drop_column('projects', 'status')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
