"""fix content_generation id autoincrement and dataclass mapping

Revision ID: 81781416bd17
Revises: 40a2397c095a
Create Date: 2025-07-16 22:21:41.546602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81781416bd17'
down_revision: Union[str, None] = '40a2397c095a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.alter_column('content_generations', 'platforms',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('content_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content_generations', 'include_news',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_content_generations_id'), table_name='content_generations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_generations_id'), 'content_generations', ['id'], unique=False)
    op.alter_column('content_generations', 'include_news',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('content_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('content_generations', 'platforms',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
