"""add_enhanced_analytics_models

Revision ID: 8d851ad8ad67
Revises: d82343b52821
Create Date: 2025-08-06 15:55:52.047080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d851ad8ad67'
down_revision: Union[str, None] = 'd82343b52821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_review_id'), 'content_review', ['id'], unique=False)
    op.create_table('analytics_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_points', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_actioned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_analytics_insights_project_id'), 'analytics_insights', ['project_id'], unique=False)
    op.create_table('analytics_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('trend_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('total_engagement', sa.Integer(), nullable=False),
    sa.Column('total_reach', sa.Integer(), nullable=False),
    sa.Column('total_impressions', sa.Integer(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_click_rate', sa.Float(), nullable=False),
    sa.Column('engagement_growth', sa.Float(), nullable=False),
    sa.Column('reach_growth', sa.Float(), nullable=False),
    sa.Column('follower_growth', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_analytics_trends_project_id'), 'analytics_trends', ['project_id'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    
    # Add columns with nullable=True first to handle existing data
    op.add_column('post_analytics', sa.Column('data_quality_score', sa.Float(), nullable=True))
    op.add_column('post_analytics', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    op.add_column('post_analytics', sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE post_analytics SET data_quality_score = 1.0 WHERE data_quality_score IS NULL")
    op.execute("UPDATE post_analytics SET is_anomaly = false WHERE is_anomaly IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('post_analytics', 'data_quality_score', nullable=False)
    op.alter_column('post_analytics', 'is_anomaly', nullable=False)
    
    # Add columns to social_media_posts with nullable=True first
    op.add_column('social_media_posts', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('social_media_posts', sa.Column('platform_post_id', sa.String(length=200), nullable=True))
    op.add_column('social_media_posts', sa.Column('post_url', sa.String(length=500), nullable=True))
    op.add_column('social_media_posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE social_media_posts SET project_id = content_generation_id WHERE project_id IS NULL")
    op.execute("UPDATE social_media_posts SET updated_at = created_at WHERE updated_at IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('social_media_posts', 'project_id', nullable=False)
    op.alter_column('social_media_posts', 'updated_at', nullable=False)
    op.alter_column('social_media_posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('social_media_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_social_media_posts_project_id'), 'social_media_posts', ['project_id'], unique=False)
    op.create_foreign_key(None, 'social_media_posts', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_media_posts', type_='foreignkey')
    op.drop_index(op.f('ix_social_media_posts_project_id'), table_name='social_media_posts')
    op.alter_column('social_media_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_media_posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('social_media_posts', 'updated_at')
    op.drop_column('social_media_posts', 'post_url')
    op.drop_column('social_media_posts', 'platform_post_id')
    op.drop_column('social_media_posts', 'project_id')
    op.drop_column('post_analytics', 'last_verified')
    op.drop_column('post_analytics', 'is_anomaly')
    op.drop_column('post_analytics', 'data_quality_score')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_analytics_trends_project_id'), table_name='analytics_trends')
    op.drop_table('analytics_trends')
    op.drop_index(op.f('ix_analytics_insights_project_id'), table_name='analytics_insights')
    op.drop_table('analytics_insights')
    op.drop_index(op.f('ix_content_review_id'), table_name='content_review')
    op.drop_table('content_review')
    # ### end Alembic commands ###
