"""Add user_id to post

Revision ID: 915185357f97
Revises: 8bdd824be734
Create Date: 2025-07-18 15:11:29.091667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '915185357f97'
down_revision: Union[str, None] = '8bdd824be734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('social_medias', sa.String(), nullable=False))
    op.add_column('post', sa.Column('text', sa.String(), nullable=False))
    op.add_column('post', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('image', sa.String(), nullable=False))
    op.add_column('post', sa.Column('posted', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'post', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'posted')
    op.drop_column('post', 'image')
    op.drop_column('post', 'scheduled_time')
    op.drop_column('post', 'text')
    op.drop_column('post', 'social_medias')
    op.drop_column('post', 'user_id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
