"""make_post_id_optional_in_post_analytics

Revision ID: d82343b52821
Revises: add_analytics_tables
Create Date: 2025-08-05 12:34:12.150177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd82343b52821'
down_revision: Union[str, None] = 'add_analytics_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.create_unique_constraint(None, 'ab_tests', ['id'])
    op.create_unique_constraint(None, 'analytics_reports', ['id'])
    op.alter_column('media_collection_items', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('media_collection_items', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_media_collection_items_collection_id'), table_name='media_collection_items')
    op.drop_index(op.f('idx_media_collection_items_media_file_id'), table_name='media_collection_items')
    op.create_index(op.f('ix_media_collection_items_id'), 'media_collection_items', ['id'], unique=False)
    op.drop_constraint(op.f('fk_collection_items_collection'), 'media_collection_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_collection_items_media_file'), 'media_collection_items', type_='foreignkey')
    op.alter_column('media_collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_media_collections_library_id'), table_name='media_collections')
    op.create_index(op.f('ix_media_collections_id'), 'media_collections', ['id'], unique=False)
    op.drop_constraint(op.f('fk_media_collections_library'), 'media_collections', type_='foreignkey')
    op.alter_column('media_edits', 'edit_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('media_edits', 'original_file_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('media_edits', 'edited_file_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('media_edits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_media_edits_media_file_id'), table_name='media_edits')
    op.drop_index(op.f('idx_media_edits_user_id'), table_name='media_edits')
    op.create_index(op.f('ix_media_edits_id'), 'media_edits', ['id'], unique=False)
    op.drop_constraint(op.f('media_edits_user_id_fkey'), 'media_edits', type_='foreignkey')
    op.drop_constraint(op.f('fk_media_edits_media_file'), 'media_edits', type_='foreignkey')
    op.drop_column('media_edits', 'is_active')
    op.drop_column('media_edits', 'original_file_path')
    op.drop_column('media_edits', 'edited_file_path')
    op.drop_column('media_edits', 'user_id')
    op.alter_column('media_files', 'file_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('media_files', 'file_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('media_files', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('media_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_media_files_file_type'), table_name='media_files')
    op.drop_index(op.f('idx_media_files_library_id'), table_name='media_files')
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.drop_constraint(op.f('fk_media_files_library'), 'media_files', type_='foreignkey')
    op.alter_column('media_libraries', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('media_libraries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_libraries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_media_libraries_id'), 'media_libraries', ['id'], unique=False)
    op.alter_column('post_analytics', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'post_analytics', ['id'])
    op.alter_column('project_media', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('project_media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_project_media_media_file_id'), table_name='project_media')
    op.drop_index(op.f('idx_project_media_project_id'), table_name='project_media')
    op.create_index(op.f('ix_project_media_id'), 'project_media', ['id'], unique=False)
    op.drop_constraint(op.f('fk_project_media_project'), 'project_media', type_='foreignkey')
    op.drop_constraint(op.f('fk_project_media_media_file'), 'project_media', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_media_media_file'), 'project_media', 'media_files', ['media_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_project_media_project'), 'project_media', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_project_media_id'), table_name='project_media')
    op.create_index(op.f('idx_project_media_project_id'), 'project_media', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_media_media_file_id'), 'project_media', ['media_file_id'], unique=False)
    op.alter_column('project_media', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('project_media', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'primary'::character varying"))
    op.drop_constraint(None, 'post_analytics', type_='unique')
    op.alter_column('post_analytics', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_media_libraries_id'), table_name='media_libraries')
    op.alter_column('media_libraries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('media_libraries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_libraries', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(op.f('fk_media_files_library'), 'media_files', 'media_libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.create_index(op.f('idx_media_files_library_id'), 'media_files', ['library_id'], unique=False)
    op.create_index(op.f('idx_media_files_file_type'), 'media_files', ['file_type'], unique=False)
    op.alter_column('media_files', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('media_files', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_files', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('media_files', 'file_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('media_files', 'file_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('media_edits', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('media_edits', sa.Column('edited_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('media_edits', sa.Column('original_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('media_edits', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_media_edits_media_file'), 'media_edits', 'media_files', ['media_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('media_edits_user_id_fkey'), 'media_edits', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_media_edits_id'), table_name='media_edits')
    op.create_index(op.f('idx_media_edits_user_id'), 'media_edits', ['user_id'], unique=False)
    op.create_index(op.f('idx_media_edits_media_file_id'), 'media_edits', ['media_file_id'], unique=False)
    op.alter_column('media_edits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_edits', 'edited_file_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('media_edits', 'original_file_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('media_edits', 'edit_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_media_collections_library'), 'media_collections', 'media_libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_media_collections_id'), table_name='media_collections')
    op.create_index(op.f('idx_media_collections_library_id'), 'media_collections', ['library_id'], unique=False)
    op.alter_column('media_collections', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('media_collections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(op.f('fk_collection_items_media_file'), 'media_collection_items', 'media_files', ['media_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_collection_items_collection'), 'media_collection_items', 'media_collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_media_collection_items_id'), table_name='media_collection_items')
    op.create_index(op.f('idx_media_collection_items_media_file_id'), 'media_collection_items', ['media_file_id'], unique=False)
    op.create_index(op.f('idx_media_collection_items_collection_id'), 'media_collection_items', ['collection_id'], unique=False)
    op.alter_column('media_collection_items', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media_collection_items', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'analytics_reports', type_='unique')
    op.drop_constraint(None, 'ab_tests', type_='unique')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
